#include "DiceHeader.h"

#include <time.h>
#include <math.h>
#include <stdlib.h>

/*****************************************************************************
Function Name: rollDice()
Purpose: randomly generate a number between 1 – 6 and
        return the number generated by rand( )
Function in parameters: void
Function out parameter: int
Version: 1
Author: Neeraj Kumar ,Ding Yi, Dutra Emilio
*****************************************************************************/
int rollDice(void)
{
    return rand() % 6 + 1;
}

/*****************************************************************************
Function Name: addRoll()
Purpose: add a roll to the rolls, and increase the rollCount by two dice results
Function in parameters: struct Roll *rolls, int *pRollCount, int dice1, int dice2
Function out parameter: void
Version: 1
Author: Neeraj Kumar ,Ding Yi, Dutra Emilio
*****************************************************************************/
void addRoll(struct Roll *rolls, int *pRollCount, int dice1, int dice2)
{
    (*pRollCount)++;
    rolls = realloc(rolls, *pRollCount * sizeof(struct Roll));
    rolls[*pRollCount - 1].dice1 = dice1;
    rolls[*pRollCount - 1].dice2 = dice2;
}


/*****************************************************************************
Function Name: printRoll()
Purpose: print the rolls result
Function in parameters: struct Roll *rolls, int rollCount, int pm
Function out parameter: void
Version: 1
Author: Neeraj Kumar ,Ding Yi, Dutra Emilio
*****************************************************************************/
void printRoll(struct Roll *rolls, int rollCount, int pm)
{
    int i;
    printf("---------------------------------------------------------------------\n");
    printf("\tROLL NUM\tDICE#1\tDICE#2\tTOTAL ROLL\tPOINT MATCH\n");
    printf("---------------------------------------------------------------------\n");
    for (i = 0; i < rollCount; ++i)
    {
        printf("\t%d\t\t%d\t%d\t%d\t\t%d\n", i, rolls[i].dice1, rolls[i].dice2, rolls[i].dice1 + rolls[i].dice2, pm);
    }
}

/*****************************************************************************
Function Name: judgeRoll()
Purpose: judge a sum of two dices can make a won or lost.
            7,11 for won
            2,3,12 for lost
            other for not won nor lost
Function in parameters: int sum
Function out parameter: void
Version: 1
Author: Neeraj Kumar ,Ding Yi, Dutra Emilio
*****************************************************************************/
int judgeRoll(int sum)
{
    if (sum == 7 || sum == 11)
    {
        return WON;
    }
    if (sum == 2 || sum == 3 || sum == 12)
    {
        return LOST;
    }
    return TIE;
}

/*****************************************************************************
Function Name: playGame()
Purpose:
    When the player is ready to play, (s)he would use the key ENTER to roll the dice
    If the user wins in his/her first roll, congratulate the player and return with WON
    If the user looses in his/her first roll, return with LOOSE and apologize
    Let the user keep playing until (s)he wins / loses, give an appropriate massage and finish
the game with the last roll value.
Function in parameters: void
Function out parameter: int, for WON/LOST/TIE(only while user want to quit)
Version: 1
Author: Neeraj Kumar ,Ding Yi, Dutra Emilio
*****************************************************************************/
int playGame(void)
{
    int pm;
    int rollCount = 0;
    struct Roll *rolls;
    rolls = malloc(0);
    while (1)
    {
        int dice1, dice2;
        int pcDice1, pcDice2;
        int sum,pcSum;

        /* let user input */
        printf("\t\t\tROLL THE DICE WITH [ENTER] QUIT TO [q] ");
        while (1)
        {
            int c = getchar();
            if (c == '\n')
            {
                /* set the random seed */
                srand(time(0));
                break;
            }

            if (c == 'q')
                return TIE;
        }

        /* roll dice for user */
        dice1 = rollDice();
        dice2 = rollDice();
        sum = dice1 + dice2;

        /* get the PM */
        if (rollCount == 0)
        {
            pm = sum;
        }

        /* add roll result to data */
        addRoll(rolls, &rollCount, dice1, dice2);
        printRoll(rolls, rollCount, pm);

        /* if user won */
        if (rollCount > 1 && sum == pm)
        {
            if (rollCount == 1)
                printf("Congratulation you rolled %d the point match, and you WIN!!!\n", sum);
            else
                printf("Congratulation you roll %d and win on your %d try\n", sum, rollCount);
            return WON;
        }

        if (judgeRoll(sum) == WON)
        {
            if (rollCount == 1)
                printf("Congratulation you rolled %d the winning match, and you WIN!!!\n", sum);
            else
                printf("Congratulation you roll %d and win on your %dth try\n", sum, rollCount);
            return WON;
        }

        /* if user lost */
        if (judgeRoll(sum) == LOST)
        {
            printf("You rolled %d the losing match. You lose.\n", sum);
            return LOST;
        }

        /* let computer roll dice */
        pcDice1 = rollDice();
        pcDice2 = rollDice();
        pcSum = pcDice1 + pcDice2;

        /* if computer won */
        if (judgeRoll(pcSum) == WON)
        {
            printf("Sorry, Computer rolled %d the winning match and you lose\n", pcSum);
            return LOST;
        }

        /* if computer lost */
        if (judgeRoll(pcSum) == LOST)
        {
            printf("Congratulation computer rolled %d the losing match, and you WIN!!!\n", pcSum);
            return WON;
        }

        /* there is a tie */
        printf("Computer rolled %d, game continues...\n", pcSum);
    }

    return TIE;
}